import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillInstagram, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import deved from "..//public/me.jpg";
import Anokhe from "../public/Anokhe.png";
import MoodSic from "../public/MoodSic.png";
import Spotify from "../public/Spotify.png";
import nextjs from "../public/nextjs.png";
import js from "../public/js.png";
import cpp from "../public/cpp.png";
import python from "../public/python.png";
import reactjs from "../public/reactjs.png";
import express from "../public/express.png";
import figma from "../public/figma.png";
import bootstrap from "../public/bootstrap.png";
import can from "../public/can.png";
import PhotographyBlog from "../public/PhotographyBlog.png";
import { useState } from "react";
import emailjs from "emailjs-com";
import React from "react";
import Contact from "./contact";
import Link from "next/link";
// import Contact from '../public/Contact';

export default function Home() {
  const [darkMode, setdarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Pritha Khanna Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-black px-10 dark:bg-white">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl text-blue-500 font-burtons">My Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setdarkMode(!darkMode)}
                  className="cursor-pointer text-2xl text-blue-500"
                />
              </li>
              <li>
                <Link href="/contact">
                  <a className="  text-blue-500 px-4 py-2 ml-8 ">Contact</a>
                </Link>
              </li>
              <li>
                <a
                  className=" bg-blue-500 text-white px-4 py-2 rounded-md ml-8"
                  href="https://docs.google.com/document/d/11zCdyyEP-KfdeoTPpcANjaq4IfzWLtOM/edit?usp=drive_link&ouid=103185548656978988518&rtpof=true&sd=true"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <h2 className=" text-red-500 text-5xl py-2">Pritha Khanna</h2>
            <h3 className=" text-blue-500 text-2xl py-2">
              Front-End Developer and Designer
            </h3>
            <p className=" text-gray-400  text-md py-5 leading-8 ">
              College student providing services for programming and designing
              content needs. Join me down below and let's get cracking!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-400">
            <a href="https://www.instagram.com/">
              {" "}
              <AiFillInstagram />
            </a>
            <a href="https://www.linkedin.com/in/pritha-khanna-a34663219/">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative rounded-full w-80 h-80 mt-10 mx-auto rounded-full">
            <Image src={deved} className="rounded-full" />
          </div>
        </section>

        <section>
          <div className="text-left mt-20">
            <h3 className="text-3xl pt-8 text-red-500">About Me</h3>
            <p className=" text-gray-400  text-md py-2 leading-8 ">
              I am a pre-final year college student with a keen interest in
              front-end development and design. Currently, I am focused on
              honing my skills to become a proficient MERN developer. I possess
              a basic understanding of data structures, algorithms, and database
              concepts. My primary goal is to upskill through collaboration,
              gaining practical experience and expanding my knowledge in this
              field.
            </p>
          </div>
          <div className="mt-15">
            <h3 className="text-3xl pt-8 pb-5 text-red-500">Work Experience</h3>
            <div>
              <ol class="relative border-l border-red-500 dark:border-red-500">
                <li class="mb-10 ml-4">
                  <div class="absolute w-3 h-3 bg-red-500 rounded-full mt-1.5 -left-1.5 border border-red-500"></div>
                  <p className=" text-blue-500  text-md py-2 leading-8 ">
                    Web Development Internship, IIT Hyderabad
                  </p>
                  <p className=" text-gray-400  text-md pb-3 leading-8 ">
                    Gained hands-on experience in deploying cutting-edge web
                    applications, collaborating on challenging projects, and
                    demonstrating problem-solving skills and adaptability in a
                    dynamic academic environment.
                  </p>
                </li>
                <li class="mb-10 ml-4">
                  <div class="absolute w-3 h-3 bg-red-500 rounded-full mt-1.5 -left-1.5 border border-red-500"></div>
                  <p className=" text-blue-500  text-md py-2 leading-8 ">
                    Fundraising Intern, Odisha Development Management Programme
                    (NGO)
                  </p>
                  <p className=" text-gray-400  text-md pb-3 leading-8 ">
                    Assist in raising funds for initiatives aimed at improving
                    the lives of waste pickers. Collaborated on innovative
                    strategies, showcasing excellent communication skills to
                    engage donors and foster meaningful partnerships.
                  </p>
                </li>
                <li class="mb-10 ml-4">
                  <div class="absolute w-3 h-3 bg-red-500 rounded-full mt-1.5 -left-1.5 border border-red-500 "></div>
                  <p className=" text-blue-500  text-md py-2 leading-8 ">
                    Content Writing Intern, Team Everest (NGO)
                  </p>
                  <p className=" text-gray-400  text-md pb-3 leading-8 ">
                    Created impactful written content, including story
                    comprehension modules for college students. Collaborated
                    with professionals, leveraging creativity and storytelling
                    skills to empower and educate college students through
                    effective written communication.
                  </p>
                </li>
              </ol>
            </div>
          </div>
          <div className="text-left mt-10">
            <h3 className="text-3xl pt-8 text-red-500 mb-4">Projects</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg-flex-wrap">
            <div className="basis-1/2 flex-1">
              <Image
                src={Anokhe}
                class="thumbnail"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                src={PhotographyBlog}
                class="thumbnail"
                lassName="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                src={MoodSic}
                class="thumbnail"
                lassName="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                src={Spotify}
                class="thumbnail"
                lassName="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
          <div className="text-left mt-6">
            <h3 className="text-3xl pt-8 text-red-500 mb-2">Skills</h3>
          </div>
          <div className="flex flex-col gap-6 py-10 lg:flex-row lg-flex-wrap">
            <div className="basis-1/7 flex-1">
              <Image
                src={nextjs}
                className="rounded-md object-cover"
                layout="responsive"
              />
            </div>
            <div className="basis-1/7 flex-1">
              <Image
                src={reactjs}
                lassName="rounded-md object-cover"
                layout="responsive"
              />
            </div>
            <div className="basis-1/7 flex-1">
              <Image
                src={js}
                lassName="rounded-lg object-cover"
                layout="responsive"
              />
            </div>
            <div className="basis-1/7 flex-1">
              <Image
                src={cpp}
                lassName="rounded-lg object-cover"
                layout="responsive"
              />
            </div>
            <div className="basis-1/7 flex-1">
              <Image
                src={python}
                lassName="rounded-lg object-cover"
                layout="responsive"
              />
            </div>
            <div className="basis-1/7 flex-1">
              <Image
                src={express}
                lassName="rounded-lg object-cover"
                layout="responsive"
              />
            </div>
            <div className="basis-1/7 flex-1">
              <Image
                src={bootstrap}
                lassName="rounded-lg object-cover"
                layout="responsive"
              />
            </div>
            <div className="basis-1/7 flex-1">
              <Image
                src={figma}
                lassName="rounded-lg object-cover"
                layout="responsive"
              />
            </div>
            <div className="basis-1/7 flex-1">
              <Image
                src={can}
                lassName="rounded-lg object-cover"
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
